services:
  health_checker_0:
    container_name: health_checker_0
    build:
      context: ./containers/
      dockerfile: health_checker/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELECTION_ID=0
      - ELECTION_REPLICAS_AMOUNT=3
      - PYTHONUNBUFFERED=1
      - SERVICES=health_checker_0,health_checker_1,health_checker_2
      - RETRIES=3

  health_checker_1:
    container_name: health_checker_1
    build:
      context: ./containers/
      dockerfile: health_checker/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELECTION_ID=1
      - ELECTION_REPLICAS_AMOUNT=3
      - PYTHONUNBUFFERED=1
      - SERVICES=health_checker_0,health_checker_1,health_checker_2
      - RETRIES=3

  health_checker_2:
    container_name: health_checker_2
    build:
      context: ./containers/
      dockerfile: health_checker/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELECTION_ID=2
      - ELECTION_REPLICAS_AMOUNT=3
      - PYTHONUNBUFFERED=1
      - SERVICES=health_checker_0,health_checker_1,health_checker_2
      - RETRIES=3

  # test_dind:
  #   container_name: test_dind
  #   build:
  #     context: ./containers/
  #     dockerfile: test_dind/Dockerfile
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - SERVICES=test_target_1,test_target_2,test_target_3

  # test_target_1:
  #   container_name: test_target_1
  #   build:
  #     context: ./containers/
  #     dockerfile: test_target/Dockerfile
  #   environment:
  #     - FAIL_AFTER=3
  #     - SKIP_AFTER=0

  # test_target_2:
  #   container_name: test_target_2
  #   build:
  #     context: ./containers/
  #     dockerfile: test_target/Dockerfile
  #   environment:
  #     - FAIL_AFTER=5
  #     - SKIP_AFTER=0

  # test_target_3:
  #   container_name: test_target_3
  #   build:
  #     context: ./containers/
  #     dockerfile: test_target/Dockerfile
  #   environment:
  #     - FAIL_AFTER=0
  #     - SKIP_AFTER=6

# services:
#   rabbitmq:
#     build:
#       context: ./containers/rabbitmq
#       dockerfile: Dockerfile
#     ports:
#       - 15672:15672
#     healthcheck:
#       test: rabbitmq-diagnostics check_port_connectivity
#       interval: 5s
#       timeout: 3s
#       retries: 10
#       start_period: 50s
#     environment:
#       - RABBITMQ_LOG_LEVELS=error

#   client:
#     container_name: client
#     build:
#       context: ./containers/
#       dockerfile: client/Dockerfile
#     environment:
#       - SERVER_PORT=25555
#       - SERVER_HOST=request_listener
#       - PYTHONUNBUFFERED=1
#     volumes:
#       - .data/output:/output
#       - .data/datasets:/datasets
#       - .data/config.ini:/root/config.ini
#     depends_on:
#       - request_listener
#     links:
#       - request_listener
#     restart: on-failure

#   request_listener:
#     container_name: request_listener
#     build:
#       context: ./containers/
#       dockerfile: request_listener/Dockerfile
#     environment:
#       - PYTHONUNBUFFERED=1
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini

#   all_countries_agg:
#     build:
#       context: ./containers/
#       dockerfile: all_countries_agg/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/id_country_files:/id_country_files
#       - .data/config.ini:/root/config.ini
#     environment:
#       - PYTHONUNBUFFERED=1
#       - COPIES=2
#     scale: 2

#   thumbnail_downloader:
#     build:
#       context: ./containers/
#       dockerfile: thumbnail_downloader/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#         condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#     environment:
#       - PYTHONUNBUFFERED=1
#       - COPIES=2
#     scale: 2

#   max_day_filter:
#     build:
#       context: ./containers/
#       dockerfile: max_day_filter/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#       - .data/date_files:/date_files
#     environment:
#       - PYTHONUNBUFFERED=1
#       - COPIES=2
#     scale: 2

#   max_day_agg:
#     build:
#       context: ./containers/
#       dockerfile: max_day_agg/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#     environment:
#       - PYTHONUNBUFFERED=1

#   adaptor1:
#     container_name: adaptor_1
#     build:
#       context: ./containers/
#       dockerfile: adaptor1-2/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#     environment:
#       - SERVICE_NAME=ADAPTOR_1
#       - PYTHONUNBUFFERED=1

#   adaptor2:
#     container_name: adaptor_2
#     build:
#       context: ./containers/
#       dockerfile: adaptor1-2/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#     environment:
#       - SERVICE_NAME=ADAPTOR_2
#       - PYTHONUNBUFFERED=1

#   likes_filter:
#     container_name: likes_filter
#     build:
#       context: ./containers/
#       dockerfile: likes_filter/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#     environment:
#       - PYTHONUNBUFFERED=1

#   tag_filter:
#     container_name: tag_filter
#     build:
#       context: ./containers/
#       dockerfile: tag_filter/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#     environment:
#       - PYTHONUNBUFFERED=1
  
#   duplicates_filter:
#     build:
#       context: ./containers/
#       dockerfile: duplicates_filter/Dockerfile
#     restart: on-failure
#     depends_on:
#       rabbitmq:
#          condition: service_healthy
#     volumes:
#       - .data/config.ini:/root/config.ini
#       - .data/id_duplicate_files:/id_duplicate_files
#     environment:
#       - COPIES=1
#     scale: 1
